
export const jobListings = [
  {
    id: "1",
    title: "Software Engineer",
    company: "Acme Corporation",
    companyLogo: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=500&auto=format&fit=crop",
    location: "Remote",
    jobType: "Full-time",
    salary: "$120,000 - $150,000",
    description:
      "We are looking for a Software Engineer to join our team. You will be responsible for building user interfaces for our web applications using React and Next.js.",
    postedDate: "2 days ago",
    isUrgent: true,
    isNew: true,
    featured: true,
    category: "Engineering",
    tags: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
  },
  {
    id: "2",
    title: "Product Manager",
    company: "TechCorp Inc.",
    companyLogo: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=500&auto=format&fit=crop",
    location: "Boston, MA",
    jobType: "Full-time",
    salary: "$110,000 - $140,000",
    description:
      "We're looking for a Product Manager to lead our product development efforts. You'll work with cross-functional teams to define product strategy and roadmap.",
    postedDate: "5 days ago",
    isUrgent: false,
    isNew: false,
    featured: true,
    category: "Product",
    tags: ["Product Strategy", "Agile", "User Stories", "Roadmapping"],
  },
  {
    id: "3",
    title: "UI Designer",
    company: "Design LLC",
    companyLogo: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=500&auto=format&fit=crop",
    location: "New York, NY",
    jobType: "Full-time",
    salary: "$90,000 - $120,000",
    description:
      "We're seeking a talented UI Designer to create beautiful, intuitive interfaces for our products. You'll work closely with our product and engineering teams.",
    postedDate: "1 week ago",
    isUrgent: false,
    isNew: false,
    featured: true,
    category: "Design",
    tags: ["Figma", "UI Design", "User Research", "Prototyping"],
  },
  {
    id: "4",
    title: "Marketing Specialist",
    company: "Media Group",
    companyLogo: "https://images.unsplash.com/photo-1611162618479-ee4a1f8d5be9?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=500&auto=format&fit=crop",
    location: "San Francisco, CA",
    jobType: "Full-time",
    salary: "$80,000 - $100,000",
    description:
      "We're looking for a Marketing Specialist to help grow our brand presence. You'll be responsible for creating and executing marketing campaigns.",
    postedDate: "3 days ago",
    isUrgent: false,
    isNew: true,
    featured: true,
    category: "Marketing",
    tags: ["Digital Marketing", "Social Media", "Content Creation", "Analytics"],
  },
  {
    id: "5",
    title: "Front-End Developer",
    company: "Cloud Solutions Inc.",
    companyLogo: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=500&auto=format&fit=crop",
    location: "Boston, MA",
    jobType: "Full-time",
    salary: "$90,000 - $120,000",
    description:
      "Great opportunity for a front-end developer to join our team. You'll work on building responsive websites and web applications using modern technologies.",
    postedDate: "1 week ago",
    isUrgent: false,
    isNew: false,
    featured: false,
    category: "Engineering",
    tags: ["HTML", "CSS", "JavaScript", "React"],
  },
  {
    id: "6",
    title: "Mobile App Designer",
    company: "Creative Apps LLC",
    companyLogo: "https://images.unsplash.com/photo-1611162617263-4ec3060a058e?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1551650975-87deedd944c3?q=80&w=500&auto=format&fit=crop",
    location: "San Francisco, CA",
    jobType: "Contract",
    salary: "$100,000 - $130,000",
    description:
      "Join our mobile design team to create innovative iOS and Android applications. You'll work with our product team to create beautiful mobile experiences.",
    postedDate: "2 weeks ago",
    isUrgent: false,
    isNew: false,
    featured: false,
    category: "Design",
    tags: ["UI/UX", "Mobile Design", "Figma", "Sketch"],
  },
  {
    id: "7",
    title: "Data Scientist",
    company: "Analytics Corp.",
    companyLogo: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=500&auto=format&fit=crop",
    location: "Remote",
    jobType: "Full-time",
    salary: "$130,000 - $160,000",
    description:
      "We're seeking a Data Scientist to help us extract insights from our data. You'll work with large datasets and build machine learning models.",
    postedDate: "3 days ago",
    isUrgent: true,
    isNew: true,
    featured: false,
    category: "Engineering",
    tags: ["Python", "Machine Learning", "Data Analysis", "SQL"],
  },
  {
    id: "8",
    title: "DevOps Engineer",
    company: "CloudWorks",
    companyLogo: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?q=80&w=100&auto=format&fit=crop", // Writing-related logo
    coverImage: "https://images.unsplash.com/photo-1516321165247-7b920bd08522?q=80&w=500&auto=format&fit=crop", // Person writing
    location: "Austin, TX",
    jobType: "Full-time",
    salary: "$125,000 - $155,000",
    description:
      "Join our DevOps team to build and maintain our cloud infrastructure. You'll work with AWS, Docker, and Kubernetes to ensure our systems are reliable and scalable.",
    postedDate: "1 day ago",
    isUrgent: true,
    isNew: true,
    featured: false,
    category: "Engineering",
    tags: ["AWS", "Docker", "Kubernetes", "CI/CD"],
  },
  {
    id: "9",
    title: "Principal Software Engineer",
    company: "Tech Innovations Inc.",
    companyLogo: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=100&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=500&auto=format&fit=crop",
    location: "Chicago, IL",
    jobType: "Full-time",
    salary: "$150,000 - $180,000",
    description:
      "We are seeking a Principal Software Engineer to lead the development of innovative software solutions. The ideal candidate will possess a strong technical background and excellent leadership qualities.",
    postedDate: "2 weeks ago",
    isUrgent: false,
    isNew: false,
    featured: false,
    category: "Engineering",
    tags: ["Java", "Architecture", "Leadership", "Cloud"],
  },
  {
    id: "10",
    title: "Sales Representative",
    company: "Global Sales Co.",
    companyLogo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=100&auto=format&fit=crop", // Generic company logo
    coverImage: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=500&auto=format&fit=crop", // HR team meeting
    location: "New York, NY",
    jobType: "Full-time",
    salary: "$70,000 - $90,000",
    description: "Join our dynamic sales team to drive revenue growth. You’ll be responsible for prospecting, qualifying leads, and closing deals.",
    postedDate: "1 day ago",
    isUrgent: false,
    isNew: true,
    featured: false,
    category: "Sales",
    tags: ["B2B", "CRM", "Negotiation"]
  },
  {
    id: "11",
    title: "Customer Support Specialist",
    company: "HelpDesk Heroes",
    companyLogo: "https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?q=80&w=100&auto=format&fit=crop", // Generic tech logo
    coverImage: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=500&auto=format&fit=crop", // Customer support team
    location: "Remote",
    jobType: "Part-time",
    salary: "$40,000 - $50,000",
    description: "Provide exceptional customer support to our clients. You’ll handle inquiries, resolve issues, and ensure customer satisfaction.",
    postedDate: "3 days ago",
    isUrgent: true,
    isNew: false,
    featured: false,
    category: "Customer Support",
    tags: ["Communication", "Problem Solving", "Zendesk"]
  },
  {
    id: "12",
    title: "HR Manager",
    company: "People First Inc.",
    companyLogo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=100&auto=format&fit=crop", // Generic company logo
    coverImage: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=500&auto=format&fit=crop", // HR team meeting
    location: "Chicago, IL",
    jobType: "Full-time",
    salary: "$100,000 - $120,000",
    description: "Lead our HR department to foster a positive work environment. You’ll oversee recruitment, employee relations, and compliance.",
    postedDate: "1 week ago",
    isUrgent: false,
    isNew: false,
    featured: true,
    category: "Human Resources",
    tags: ["Recruitment", "Employee Relations", "Compliance"]
  },
  {
    id: "13",
    title: "Financial Analyst",
    company: "Money Matters LLC",
    companyLogo: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=100&auto=format&fit=crop", // Finance-related logo
    coverImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=500&auto=format&fit=crop", // Financial charts
    location: "San Francisco, CA",
    jobType: "Full-time",
    salary: "$90,000 - $110,000",
    description: "Analyze financial data to support strategic decision-making. You’ll create reports, build models, and forecast trends.",
    postedDate: "2 days ago",
    isUrgent: false,
    isNew: true,
    featured: false,
    category: "Finance",
    tags: ["Excel", "Financial Modeling", "Forecasting"]
  },
  {
    id: "14",
    title: "Content Writer",
    company: "Creative Content Agency",
    companyLogo: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?q=80&w=100&auto=format&fit=crop", // Writing-related logo
    coverImage: "https://images.unsplash.com/photo-1516321165247-7b920bd08522?q=80&w=500&auto=format&fit=crop", // Person writing
    location: "Los Angeles, CA",
    jobType: "Contract",
    salary: "$50,000 - $70,000",
    description: "Create engaging content for our clients’ websites and marketing materials. You’ll write blog posts, articles, and social media content.",
    postedDate: "5 days ago",
    isUrgent: false,
    isNew: false,
    featured: false,
    category: "Marketing",
    tags: ["SEO", "Copywriting", "Blogging"]
  },
  {
    id: "15",
    title: "UX Researcher",
    company: "User Insights Ltd.",
    companyLogo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=100&auto=format&fit=crop", // Generic logo (reused)
    coverImage: "https://images.unsplash.com/photo-1552581234-26160f608093?q=80&w=500&auto=format&fit=crop", // UX research setting
    location: "Boston, MA",
    jobType: "Full-time",
    salary: "$80,000 - $100,000",
    description: "Conduct user research to inform product design decisions. You’ll perform interviews, usability tests, and analyze user behavior.",
    postedDate: "1 week ago",
    isUrgent: false,
    isNew: false,
    featured: true,
    category: "Design",
    tags: ["User Interviews", "Usability Testing", "Qualitative Research"]
  },
  {
    id: "16",
    title: "Backend Developer",
    company: "ServerSide Solutions",
    companyLogo: "https://images.unsplash.com/photo-1664574654529-b60630f33fdb?q=80&w=100&auto=format&fit=crop", // Tech logo
    coverImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=500&auto=format&fit=crop", // Tech setup (reused)
    location: "Austin, TX",
    jobType: "Full-time",
    salary: "$110,000 - $130,000",
    description: "Build and maintain our backend systems. You’ll work with Node.js, Express, and MongoDB to develop scalable APIs.",
    postedDate: "3 days ago",
    isUrgent: true,
    isNew: true,
    featured: false,
    category: "Engineering",
    tags: ["Node.js", "Express", "MongoDB", "API Development"]
  },
  {
    id: "17",
    title: "Project Manager",
    company: "Agile Projects Inc.",
    companyLogo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=100&auto=format&fit=crop", // Generic logo (reused)
    coverImage: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=500&auto=format&fit=crop", // Team meeting (reused)
    location: "Seattle, WA",
    jobType: "Full-time",
    salary: "$95,000 - $115,000",
    description: "Lead projects from inception to completion. You’ll coordinate teams, manage timelines, and ensure deliverables meet quality standards.",
    postedDate: "2 weeks ago",
    isUrgent: false,
    isNew: false,
    featured: false,
    category: "Product",
    tags: ["Scrum", "Kanban", "Jira", "Stakeholder Management"]
  },
  {
    id: "18",
    title: "Graphic Designer",
    company: "Visual Vibes Studio",
    companyLogo: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?q=80&w=100&auto=format&fit=crop", // Design logo (reused)
    coverImage: "https://images.unsplash.com/photo-1516321165247-7b920bd08522?q=80&w=500&auto=format&fit=crop", // Design workspace (reused)
    location: "Miami, FL",
    jobType: "Part-time",
    salary: "$45,000 - $55,000",
    description: "Create visually stunning graphics for our clients. You’ll design logos, marketing materials, and digital assets.",
    postedDate: "1 day ago",
    isUrgent: true,
    isNew: true,
    featured: false,
    category: "Design",
    tags: ["Adobe Creative Suite", "Branding", "Illustration"]
  },
  {
    id: "19",
    title: "Data Analyst",
    company: "Data Driven Decisions",
    companyLogo: "https://images.unsplash.com/photo-1664574654529-b60630f33fdb?q=80&w=100&auto=format&fit=crop", // Tech logo (reused)
    coverImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=500&auto=format&fit=crop", // Data charts (reused)
    location: "Remote",
    jobType: "Full-time",
    salary: "$85,000 - $105,000",
    description: "Analyze data to provide actionable insights. You’ll work with SQL, Python, and Tableau to visualize and interpret data trends.",
    postedDate: "4 days ago",
    isUrgent: false,
    isNew: false,
    featured: true,
    category: "Engineering",
    tags: ["SQL", "Python", "Tableau", "Data Visualization"]
  }
];